num_images: 7500
exp_time: 0.004
file_path: 0
file_name: 20230421_kitkat_speed18_incline20 # session number automatically appends to date
framerate: hardware
trigger_line: Line3 # not used if framerate is not "hardware"
